version: '3.8'

services:
  next-store-server:
    image: trantu30950/next-store-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-store-server
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - ./.env:/app/.env
    env_file:
      - ./.env
    command: npm run dev  